name: Main

on:
  workflow_dispatch:
  push:
    paths:
      # run when actions or source code are changed
      - .github/workflows/**
      - src/**
      - Cargo.toml
      - Cargo.lock
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run Cargo build step and cache for later
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build

  lint:
    runs-on: ubuntu-latest
    needs: build

    env:
      RUSTFLAGS: -Dwarnings

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build

      - name: Lint
        run: cargo clippy --all-targets --all-features

  # Tests the ODAWG library
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build

      - name: Test
        # we run testing seperately as it can be done without rebuilding
        # whilst `cargo tarpaulin` does tests, it often needs to rebuild
        # the entire library due to using vastly different compiler flags
        #
        # doing it this way allows testing to fail quickly if a test fails
        run: cargo test --tests

      - name: Install `cargo tarpaulin`
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-tarpaulin

      - name: Coverage
        run: cargo tarpaulin --out=Html

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Report
          path: ./tarpaulin-report.html
